export const pickColumns = [
    {
        dataField: "id",
        text: "ID",
        hidden: true,
    },
    {
        dataField: "league",
        text: "League",
        sort: true
    },
    {
        dataField: "homeTeam",
        text: "Home Team",
    },
    {
        dataField: "awayTeam",
        text: "Away Team",
    },
    {
        dataField: "prediction",
        text: "Prediction",
        sort: true
    },
    {
        dataField: "odds",
        text: "Odds",
        sort: true
    },
    {
        dataField: "date",
        text: "Date",
    },
];


export const latestPicks = [
  {
    id: 1,
    country: 'Belgium',
    league: 'BelgianFirst',
    homeTeam: 'Eupen',
    awayTeam: 'Antwerp',
    prediction: 'X',
    odds: '3.55',
    result: 'Loss',
    netUnits: '-1',
    date: '11/9/2021'
  },
  {
    id: 2,
    country: 'Belgium',
    league: 'BelgianFirst',
    homeTeam: 'Oud-Heverlee Leuven',
    awayTeam: 'Kortrijk',
    prediction: 'X',
    odds: '3.55',
    result: 'Loss',
    netUnits: '-1',
    date: '12/9/2021'
  },
  {
    id: 3,
    country: 'Belgium',
    league: 'BelgianFirst',
    homeTeam: 'Beerschot VA',
    awayTeam: 'St Truiden',
    prediction: 'X',
    odds: '3.41',
    result: 'Loss',
    netUnits: '-1',
    date: '13/9/2021'
  },
  {
    id: 4,
    country: 'England',
    league: 'PremierLeague',
    homeTeam: 'Brentford',
    awayTeam: 'Brighton',
    prediction: '2',
    odds: '2.66',
    result: 'Win',
    netUnits: '1.66',
    date: '11/9/2021'
  },
  {
    id: 5,
    country: 'England',
    league: 'PremierLeague',
    homeTeam: 'Watford',
    awayTeam: 'Wolves',
    prediction: '2',
    odds: '2.29',
    result: 'Win',
    netUnits: '1.29',
    date: '11/9/2021'
  },
  {
    id: 6,
    country: 'France',
    league: 'Ligue 1',
    homeTeam: 'Lorient',
    awayTeam: 'Lille',
    prediction: '2',
    odds: '2.257',
    result: 'Loss',
    netUnits: '-1',
    date: '10/9/2021'
  },
  {
    id: 7,
    country: 'France',
    league: 'Ligue1',
    homeTeam: 'Monaco',
    awayTeam: 'Marseille',
    prediction: 'X',
    odds: '3.56',
    result: 'Loss',
    netUnits: '-1',
    date: '11/9/2021'
  },
  {
    id: 8,
    country: 'France',
    league: 'Ligue1',
    homeTeam: 'Montpellier',
    awayTeam: 'St Etienne',
    prediction: 'X',
    odds: '3.45',
    result: 'Loss',
    netUnits: '-1',
    date: '12/9/2021'
  },
  {
    id: 9,
    country: 'France',
    league: 'Ligue1',
    homeTeam: 'Metz',
    awayTeam: 'Troyes',
    prediction: 'X',
    odds: '3.26',
    result: 'Loss',
    netUnits: '-1',
    date: '12/9/2021'
  },
  {
    id: 10,
    country: 'France',
    league: 'Ligue1',
    homeTeam: 'Brest',
    awayTeam: 'Angers',
    prediction: '1',
    odds: '2.62',
    result: 'Loss',
    netUnits: '-1',
    date: '12/9/2021'
  },
  {
    id: 11,
    country: 'Germany',
    league: 'Bundesliga',
    homeTeam: 'Leverkusen',
    awayTeam: 'Dortmund',
    prediction: '2',
    odds: '2.15',
    result: 'Win',
    netUnits: '1.15',
    date: '11/9/2021'
  },
  {
    id: 12,
    country: 'Germany',
    league: 'Bundesliga',
    homeTeam: 'Ein Frankfurt',
    awayTeam: 'Stuttgart',
    prediction: '2',
    odds: '3.41',
    result: 'Loss',
    netUnits: '-1',
    date: '12/9/2021'
  },
  {
    id: 13,
    country: 'Germany',
    league: 'Bundesliga',
    homeTeam: 'Bochum',
    awayTeam: 'Hertha',
    prediction: '2',
    odds: '2.55',
    result: 'Win',
    netUnits: '1.55',
    date: '12/9/2021'
  },
  {
    id: 14,
    country: 'Italy',
    league: 'SerieA',
    homeTeam: 'Napoli',
    awayTeam: 'Juventus',
    prediction: 'X',
    odds: '3.46',
    result: 'Loss',
    netUnits: '-1',
    date: '11/9/2021'
  },
  {
    id: 15,
    country: 'Italy',
    league: 'SerieA',
    homeTeam: 'Milan',
    awayTeam: 'Lazio',
    prediction: '2',
    odds: '3.19',
    result: 'Loss',
    netUnits: '-1',
    date: '12/9/2021'
  },
  {
    id: 16,
    country: 'Italy',
    league: 'SerieA',
    homeTeam: 'Cagliari',
    awayTeam: 'Genoa',
    prediction: '1',
    odds: '2.12',
    result: 'Loss',
    netUnits: '-1',
    date: '12/9/2021'
  },
  {
    id: 17,
    country: 'Portugal',
    league: 'PrimeiraLiga',
    homeTeam: 'Sp Lisbon',
    awayTeam: 'Porto',
    prediction: 'X',
    odds: '3.17',
    result: 'Win',
    netUnits: '2.17',
    date: '11/9/2021'
  },
  {
    id: 18,
    country: 'Portugal',
    league: 'PrimeiraLiga',
    homeTeam: 'Gil Vicente',
    awayTeam: 'Vizela',
    prediction: '2',
    odds: '3.74',
    result: 'Loss',
    netUnits: '-1',
    date: '12/9/2021'
  },
  {
    id: 19,
    country: 'Portugal',
    league: 'PrimeiraLiga',
    homeTeam: 'Moreirense',
    awayTeam: 'Famalicao',
    prediction: 'X',
    odds: '3.15',
    result: 'Win',
    netUnits: '2.15',
    date: '12/9/2021'
  },
  {
    id: 20,
    country: 'Portugal',
    league: 'PrimeiraLiga',
    homeTeam: 'Boavista',
    awayTeam: 'Portimonense',
    prediction: '2',
    odds: '2.87',
    result: 'Loss',
    netUnits: '-1',
    date: '12/9/2021'
  },
  {
    id: 21,
    country: 'Scotland',
    league: 'ScottishPL',
    homeTeam: 'Dundee',
    awayTeam: 'Livingston',
    prediction: 'X',
    odds: '3.21',
    result: 'Win',
    netUnits: '2.21',
    date: '11/9/2021'
  },
  {
    id: 22,
    country: 'Scotland',
    league: 'ScottishPL',
    homeTeam: 'Motherwell',
    awayTeam: 'Aberdeen',
    prediction: '1',
    odds: '2.9',
    result: 'Win',
    netUnits: '1.9',
    date: '11/9/2021'
  },
  {
    id: 23,
    country: 'Spain',
    league: 'Liga',
    homeTeam: 'Espanol',
    awayTeam: 'Ath Madrid',
    prediction: 'X',
    odds: '3.32',
    result: 'Loss',
    netUnits: '-1',
    date: '12/9/2021'
  },
  {
    id: 24,
    country: 'Spain',
    league: 'Liga',
    homeTeam: 'Osasuna',
    awayTeam: 'Valencia',
    prediction: 'X',
    odds: '3.12',
    result: 'Loss',
    netUnits: '-1',
    date: '12/9/2021'
  },
  {
    id: 25,
    country: 'Spain',
    league: 'Liga',
    homeTeam: 'Getafe',
    awayTeam: 'Elche',
    prediction: 'X',
    odds: '3.32',
    result: 'Loss',
    netUnits: '-1',
    date: '13/9/2021'
  },
  {
    id: 26,
    country: 'Spain',
    league: 'Liga',
    homeTeam: 'Granada',
    awayTeam: 'Betis',
    prediction: '2',
    odds: '2.36',
    result: 'Win',
    netUnits: '1.36',
    date: '13/9/2021'
  }
]